name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - testing_net
    restart: on-failure
    volumes:
      - ./server/config.ini:/config.ini:ro
      - ./bets.csv:/bets.csv:rw

  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=1
      - AGENCIA=1
      - NOMBRE=Santiago Lionel
      - APELLIDO=Lorca
      - DOCUMENTO=30904465
      - NACIMIENTO=1999-03-17
      - NUMERO=7574
    networks:
      - testing_net
    depends_on:
      - server
    restart: on-failure
    volumes:
      - ./client/config.yaml:/config.yaml:ro

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=2
      - AGENCIA=2
      - NOMBRE=María José
      - APELLIDO=González
      - DOCUMENTO=32123456
      - NACIMIENTO=1995-07-22
      - NUMERO=1234
    networks:
      - testing_net
    depends_on:
      - server
    restart: on-failure
    volumes:
      - ./client/config.yaml:/config.yaml:ro

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=3
      - AGENCIA=3
      - NOMBRE=Carlos Alberto
      - APELLIDO=Pérez
      - DOCUMENTO=28765432
      - NACIMIENTO=1992-11-30
      - NUMERO=5678
    networks:
      - testing_net
    depends_on:
      - server
    restart: on-failure
    volumes:
      - ./client/config.yaml:/config.yaml:ro

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=4
      - AGENCIA=4
      - NOMBRE=Ana Laura
      - APELLIDO=Rodríguez
      - DOCUMENTO=35098765
      - NACIMIENTO=2000-02-14
      - NUMERO=9012
    networks:
      - testing_net
    depends_on:
      - server
    restart: on-failure
    volumes:
      - ./client/config.yaml:/config.yaml:ro

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
      - CLI_ID=5
      - AGENCIA=5
      - NOMBRE=Luis Fernando
      - APELLIDO=Martínez
      - DOCUMENTO=29876543
      - NACIMIENTO=1998-09-05
      - NUMERO=3456
    networks:
      - testing_net
    depends_on:
      - server
    restart: on-failure
    volumes:
      - ./client/config.yaml:/config.yaml:ro

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
